imx-gpu-viv-v6.inc: Prevent Debian renaming for libvulkan-imx package
There is a package naming conflict with vulkan loader because of the Debian renaming.
Adding libvulkan-imx to the python function fixes the following error:

ERROR: vulkan-loader-validation-layers-+gitAUTOINC+79a99540d1-r0 do_packagedata: The recipe vulkan-loader-validation-layers is                 trying to install files into a shared area when those files already exist. Those files and their manifest location are:
   /home/neena/vulkan/build-fb/tmp/sysroots/imx8dvsabreauto/pkgdata/runtime-reverse/libvulkan-dev
 Matched in manifest-imx8dvsabreauto-imx-gpu-viv.packagedata
 /home/neena/vulkan/build-fb/tmp/sysroots/imx8dvsabreauto/pkgdata/runtime-reverse/libvulkan1
 Matched in manifest-imx8dvsabreauto-imx-gpu-viv.packagedata

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>