mesa: Update SRC_URI to use 9.2.5 for ${PV}
The following error occurs if we use ${PV} instead of 9.2.5

Exception: ExpansionError: Failure expanding variable SRCPV, expression was
${@bb.fetch2.get_srcrev(d)} which triggered exception RuntimeError: maximum recursion depth
exceeded in __insta

Signed-off-by: Neena Busireddy <neena.busireddy@freescale.com>